#!/bin/bash -l
#SBATCH --ntasks-per-node=8
#SBATCH --nodes=4
#SBATCH --array=5
#SBATCH --partition=cluster
#SBATCH --mem=24G
#SBATCH --time=25:00:00
#SBATCH --output=/home/cosmo/stephan.rasp/2016052900/B3ens/array%a.out
#SBATCH --error=/home/cosmo/stephan.rasp/2016052900/B3ens/array%a.err
#SBATCH --export=NONE
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=s.rasp@lmu.de 
#SBATCH --job-name=B32905
    
# load modules
module load icc/16.0.2 intelmpi/5.1.1 
module load netcdf/4.4.0-icc-16 grib_api/1.15.0-icc-16 grib_dwd/20110128-icc-16
    
# perform the actual work
echo "Current task is $SLURM_ARRAY_TASK_ID ..."

#################################################
# Settings (for convenience all the important settings are defined at the top)
#################################################

# Define times
DATE=2016052900
# Simulation start and stop in hours
HSTART=0
HSTART_DT=`expr $HSTART \* 144`
HSTOP=24
HSTOP_DT=`expr $HSTOP \* 144`

# Define path to cosmo executable
COSMOEXE=/home/s/S.Rasp/COSMO/cosmo_flo_psp/lmparbin_all

# Define paths to input and output directories
WORKDIR=/home/cosmo/florian.baur/cases/${DATE}
# 1. Interpolated COSMO-7km data
INDIR=$WORKDIR/input_cosmoDE

# 2. This is the output directory
OUTDIR=/home/cosmo/stephan.rasp/${DATE}/B3ens/$SLURM_ARRAY_TASK_ID/
# Now let's create this output directory if it doesnt exist yet
mkdir -p $OUTDIR
tar zxvf /home/s/S.Rasp/COSMO/cosmo_flo_psp/LOCAL/TWOMOM/dmin_wetgrowth_lookup_2mom.tgz -C $OUTDIR



# Define grid
# 1. grid points
IE=421
JE=461
KE=50
# 2. Location of rotated pole
POLLON=-170.0
POLLAT=40
# 3. Domain location
STARTLON=-5.0
STARTLAT=-5.0

# Define how many processors are used in x and y direction
NPX=4
NPY=8
NPIO=0

# PSP scheme parameters
BLPERTFLAG=.TRUE.
NSEED=$SLURM_ARRAY_TASK_ID



# OUTPUT setting are defined below


#################################################
# Change directory and create NAMELIST for INT2LM
#################################################
# Copy this runscript

#Change to working and output directory
cd $OUTDIR
rm -f YU* M_* l* cosmo.out
rm -f INPUT*
rm -f batchjob
rm -f cosmo.out



# Create INPUT Namelist with cat
# This creates a text file which contains all the necessary information 
# for COSMO in OUTPUT directory
# &GRIBOUT contains information about which fields are written in OUTPUT
# This setting contains all the fields necessary to start a COSMO2.8km run

cat > INPUT_ORG << end_input_org
 &LMGRID
  startlon_tot  = $STARTLON,  startlat_tot  =  $STARTLAT,
  pollon=$POLLON,        pollat=$POLLAT,
  dlon=0.025,         dlat=0.025,
  ie_tot=$IE,         je_tot=$JE,          ke_tot=$KE,
 /
 &RUNCTL
  hstart = $HSTART,   hstop = $HSTOP,    dt      = 25.0,    
  ydate_ini='$DATE',  nprocx = $NPX,  nprocy = $NPY,   nprocio = $NPIO,
  lphys      = .TRUE., luse_rttov    = .FALSE., luseobs = .FALSE., 
  leps = .FALSE., lreorder   = .FALSE., lreproduce    = .TRUE.,  
  ldatatypes = .FALSE., ltime_barrier = .FALSE., 
  ncomm_type=3, nboundlines= 3, idbg_level=100, ldump_ascii=.FALSE., 
  lartif_data=.FALSE, ldiagnos   = .FALSE., 
  luseblpert   = $BLPERTFLAG, 
  itype_blpert=1,
  blpert_sigma=2.5,
  blpert_const=2.0,     ! prefactor, previously hardcoded
  blpert_fixedtime=600.0,  ! time step of changing the perturbations in seconds
  seed_val=$NSEED,
    lseed_use_starttime=.TRUE.,
 /
 &TUNING
  clc_diag  =   0.5,
  pat_len   = 500.0,
  tur_len   = 150.0,
  rlam_heat =   1.0,
  rlam_mom  =   0.0,
  rat_lam   =   1.0,
  rat_can   =   1.0,
  rat_sea   =  20.0,
  c_lnd     =   2.0,
  c_soil    =   1.0,
  c_sea     =   1.5,
  z0m_dia   =   0.2,
  crsmin    = 150.0,
  wichfakt  =   0.0,
  qc0       =   0.0002,
  q_crit    =   1.6,
  mu_rain   =   0.5,
  rain_n0_factor = 0.1,
  v0snow    =    20,
  tkhmin    =   0.4,
  tkmmin    =   0.4,
  gkwake    =   0.8,
 /
end_input_org

cat > INPUT_SAT  << end_input_sat
 &SATCTL
 /
end_input_sat

cat > INPUT_IO  << end_input_io
 &IOCTL
  lasync_io=.FALSE, ngribout=1, yform_read='ncdf',
 /
 &GRIBIN
  lan_t_so0=.TRUE., lan_t_cl=.TRUE., lan_w_cl=.TRUE., lan_vio3=.TRUE.,
  lan_hmo3=.TRUE., lan_plcov=.TRUE., lan_lai=.TRUE., lan_rootdp=.TRUE.,
  lan_t_snow=.TRUE., lan_w_i=.TRUE., lan_w_snow=.TRUE., lan_rho_snow=.TRUE.,
  lan_w_so=.TRUE.,
  hincbound=1.0,
  lchkini    = .TRUE.,  lchkbd    = .TRUE.,  lbdana=.FALSE.,
  lana_qi    = .TRUE.,  llb_qi    = .TRUE.,  lana_rho_snow=.FALSE., 
  lana_qr_qs = .TRUE.,  llb_qr_qs = .TRUE.,
!  lana_qg    = .TRUE.,  llb_qg    = .FALSE.,
  ydirini='$INDIR',  ydirbd='$INDIR',
 /
 &GRIBOUT
    ! 30min output, 3D, velocity definition variables
    ncomb=0,$HSTOP_DT,72, lcheck=.FALSE., lwrite_const=.TRUE., nunit_of_time=1, 
    ydir='$OUTDIR',yform_write='ncdf',
  yvarml='P'        ,'PMSL'     ,'PS'        ,
         'U'        ,'V'        ,'W'        ,
         'T'        ,'QV'    ,
         'TOT_PREC'  ,'CAPE_ML'  ,'CIN_ML'    ,
         'LCL_ML'    ,'LFC_ML'   ,'TOT_PR    '
 /
end_input_io

cat > INPUT_DYN << end_input_dyn
 &DYNCTL
! changed by UB from newest COSMO-DE runscript from DWD:
    l2tls=.TRUE., lcond=.TRUE., ldyn_bbc=.FALSE., ldiabf_lh=.TRUE.,
    l_diff_Smag=.TRUE., y_scalar_advect='BOTT2_STRANG', 
    lspubc=.TRUE.,
    itype_hdiff=2, hd_dhmax=250.,
    hd_corr_trcr_bd=0.0, hd_corr_t_bd=0.75, hd_corr_u_bd=0.75, hd_corr_p_bd=0.75,
    hd_corr_trcr_in=0.0, hd_corr_t_in=0.0,  hd_corr_u_in=0.1,  hd_corr_p_in=0.0,
    irunge_kutta=1, irk_order=3, iadv_order=5, itype_fast_waves=2,
    itype_bbc_w=114,
    nrdtau=5, xkd=0.1,
    rlwidth=50000.0, itype_outflow_qrsg=2,
 /
end_input_dyn


cat > INPUT_PHY << end_input_phy
 &PHYCTL
   lgsp=.TRUE.,
      !itype_gscp=4,   !1-Momenten Schema
      itype_gscp=2483, ! 2 Momenten Schema
      !CCN intermediate/high/very high: 2473/2483/2493
      lsuper_coolw=.TRUE.,
    lrad=.TRUE.,
      nradcoarse=2,
      lradf_avg=.TRUE.
      hincrad=0.25,
      lforest=.TRUE.,
!      itype_albedo=3,
    ltur=.TRUE.,
      ninctura=1,
      lexpcor=.FALSE.,
      ltmpcor=.FALSE.,
      lprfcor=.FALSE.,
      lnonloc=.FALSE.,
      lcpfluc=.FALSE.,
      limpltkediff=.TRUE.,
      itype_turb=3,
      imode_turb=1,
      itype_tran=2,
      imode_tran=1,
      itype_wcld=2,
      icldm_rad =4,
      icldm_turb=2,
      icldm_tran=0,
      itype_synd=2,
    lsoil=.TRUE.,
      itype_evsl=2,
      itype_trvg=2,
      lmulti_layer=.TRUE.,
      lmelt=.TRUE.,
      lmelt_var=.TRUE.,
      ke_soil = 7,
      czml_soil = 0.005, 0.02, 0.06, 0.18, 0.54, 1.62, 4.86, 14.58,
    lconv=.TRUE.,
      lcape=.FALSE.,
      lconf_avg=.TRUE.,
      lconv_inst=.TRUE.,
      itype_conv=3,
      nincconv=10,
    llake=.FALSE.,
    lseaice=.FALSE.,
    lsso=.FALSE.,
      ltkesso=.TRUE.,
 /
end_input_phy

cat > INPUT_DIA << end_input_dia
 &DIACTL
  n0meanval=0, nincmeanval=1,
 /
end_input_dia

cat > INPUT_EPS << end_input_eps
 &EPSCTL
  iepsmem=0, iepstyp=55, iepstot=15,
 /
end_input_eps

cat > INPUT_ASS << end_input_ass
 &NUDGING
  lnudge  =.FALSE.,
 /
end_input_ass

# The input file above are now saved in the OUTDIR directory and contain all 
# the necessary information to run COSMO.

# Below are specific cluster commands

#################################################
# Queue and cluster settings
#################################################


ulimit -s unlimited 
mpirun $COSMOEXE
