#!/bin/bash
#
# This is a runscript (a shell script) to interpolate COSMO-7km data to COSMO-2.8km 
# grid to use as initial and boundary conditions
# Comments by Stephan Rasp, LMU, s.rasp@lmu.de

# To submit this job, type ./<name of this file>

#################################################
# Settings (for convenience all the important settings are defined at the top)
#################################################

# Define path to int2lm executable
INTLMEXE=/home/s/S.Rasp/COSMO/makeint2lm/tstint2lm 

# Define paths to input and output directories
# 1. This is where the ECMWF data is
INDIR=/project/meteo/w2w/Unwetter2016/icbc/
# 2. This is where the interpolated output data is supposed to go
OUTDIR=/home/scratch/users/stephan.rasp/2016060400/dein_ceu/
# Now let's create this output directory if it doesnt exist yet
mkdir -p $OUTDIR

# Define paths to external file (this is where constant fields are saved)
# Check below if file formats and the type of input is correct
# 2. Directory where output external file is located
OUTEXTDIR=/home/cosmo/stephan.rasp/ext
# 3. Name of output external file
OUTEXTNAME=lm_d0_02800_1605x1605.mol.g1
# 4. Grid points of external file
IEEXT=1605
JEEXT=1605

# Define times
DATEEU=2016060400
DATEDE=2016060400
# Simulation length in hours
HSTOP=24
# Output boundary condition frequency in hours
HINCBOUND=1

# Define input grid
# 1. Input grid points (ie->lon; je->lat; ke-> height)
IEIN=665
JEIN=657
KEIN=40
# 2. Input domain location
LONIN=-18
LATIN=-20
# 3. Input rotated pole location
POLLONIN=-170
POLLATIN=40

# Define output grid
# 1. Output grid points
IEOUT=357
JEOUT=357
KEOUT=50
# 2. Output rotated pole location
POLLONOUT=-170
POLLATOUT=40
# 3. Output domain location
LONOUT=-4.45
LATOUT=-3.45

# Define how many processors are used in x and y direction
NPX=1
NPY=1
NPIO=0

#################################################
# Change directory and create NAMELIST for INT2LM
#################################################
# Copy this runscript
cp $0 $OUTDIR/.

#Change to working and output directory
cd $OUTDIR

# REMOVE OLD FILES!!! 
rm -f YU* M_*
rm -f INPUT*
rm -f batchjob
rm -f cosmo.out


# Create INPUT Namelist with cat
# This creates a text file which contains all the necessary information 
# for INT2LM in OUTPUT directory

cat > INPUT << end_input
 &CONTRL
  ydate_bd='$DATEEU', ydate_ini='$DATEDE',
  linitial=.TRUE., lboundaries=.TRUE.,
  hstart=0.0, hstop=$HSTOP, hincbound=$HINCBOUND,
  nprocx=$NPX, nprocy=$NPY, nprocio=0,
  yinput_model='COSMO',
  lfilter_oro=.true., lfilter_pp=.true., lbalance_pp=.true.,
  eps_filter=0.1, norder_filter=5,
  ilow_pass_oro=4, ilow_pass_xso=5,
  lasync_io=.false., lreorder=.false., lroutine=.false., ltime_mean=.true.,
  lmulti_layer_in=.true., lmulti_layer_lm=.true.,
  lprog_qi=.true., lprog_qr_qs=.TRUE., lprog_rho_snow=.TRUE.,
  lforest=.true., lt_cl_corr=.false., luvcor=.true.,
  lvertwind_ini=.true., lvertwind_bd=.true.,
  rxso_mask=625.0,
  idbg_level=2,
 /
 &GRID_IN
  startlon_in_tot=$LONIN, startlat_in_tot=$LATIN,  
  pollat_in=$POLLATIN,        pollon_in=$POLLONIN,
  dlat_in=0.0625,        dlon_in=0.0625,
  ie_in_tot=$IEIN, je_in_tot=$JEIN, ke_in_tot=$KEIN,
 /
 &LMGRID
  startlat_tot=$LATOUT, startlon_tot=$LONOUT,
  pollat=$POLLATOUT, pollon=$POLLONOUT,
  dlon=0.025, dlat=0.025,
  ielm_tot=$IEOUT, jelm_tot=$JEOUT, kelm_tot=$KEOUT,
  ivctype=2, vcflat=11357.0,
  vcoord_d=22000.00,21000.00,20028.57,19085.36,18170.00,17282.14,
           16421.43,15587.50,14780.00,13998.57,13242.86,12512.50,
           11807.14,11126.43,10470.00, 9837.50, 9228.57, 8642.86,
            8080.00, 7539.64, 7021.43, 6525.00, 6050.00, 5596.07,5162.86,
            4750.00, 4357.14, 3983.93, 3630.00, 3295.00, 2978.57,2680.36,
            2400.00, 2137.14, 1891.43, 1662.50, 1450.00, 1253.57,1072.86,
             907.50,  757.14,  621.43,  500.00,  392.50,  298.57, 217.86,
             150.00,   94.64,   51.43,   20.00,    0.00,
 /
 &DATABASE
 /
 &DATA
  ie_ext=$IEEXT, je_ext=$JEEXT,
  ylmext_lfn='$OUTEXTNAME',
  ylmext_cat='$OUTEXTDIR',
  ylmext_form_read='apix',
  yinext_lfn='laf$DATEDE',
  yinext_form_read='apix',
  yinext_cat='$INDIR',
  yin_cat='$INDIR',
  yin_form_read='apix',
  ylm_cat='$OUTDIR',
  yinput_type='analysis',
  nprocess_ini = 137, nprocess_bd = 138, 
  ytunit_in='f',
  ytunit_out='f',
  ylm_form_write='grb1',
  l_ke_in_gds=.TRUE.,
  nl_soil_in=2, nl_soil_lm=2,
  yin_hhl='laf$DATEDE'
 /
 &PRICTR
 /
end_input


# Now all the settings for the INT2LM run are complete and saved in the 
# INPUT namelist file. 
# If you run the INTLMEXE file in this directory now it should work.

# What follows below are setting for the cluster and the parallel environment.
# This is specific for each cluster.


#################################################
# Queue and cluster settings
#################################################


#Calculade Nodes
NP1=`expr $NPX \* $NPY`
NP=`expr $NP1 + $NPIO`
N1=`expr $NP + 15`
NODES=`expr $N1 \/ 16`

#Define Exp-Label for queue
QLABEL=i160604


# Create batchjob
cat > batchjob << end_batchjob
#!/bin/bash -l
#SBATCH --ntasks-per-node=$NP
#SBATCH --nodes=1
#SBATCH --mem=8G
#SBATCH --time=1:00:00
#SBATCH --output=/home/scratch/users/stephan.rasp/2016060400/dein_ceu//cosmo.out
#SBATCH --error=/home/scratch/users/stephan.rasp/2016060400/dein_ceu//slurm.err
#SBATCH --export=NONE
#SBATCH --job-name=$QLABEL
#SBATCH --partition=cluster,ws
# load modules
module load icc/16.0.2 intelmpi/5.1.1 grib_api/1.13.1-icc-16 netcdf/4.4.0-icc-16 grib_dwd/20110128-icc-16
ulimit -s unlimited 
mpirun -np $NP $INTLMEXE
end_batchjob


# Submit job
chmod u+x batchjob
sbatch batchjob

# #SBATCH --mail-type=END
# #SBATCH --mail-user=s.rasp@lmu.de 
