#!/bin/bash -l
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --array=1-16
#SBATCH --partition=cluster,ws
#SBATCH --mem=24G
#SBATCH --time=1:00:00
#SBATCH --output=/home/cosmo/stephan.rasp/2016053100/dein//array%a.out
#SBATCH --error=/home/cosmo/stephan.rasp/2016053100/dein//array%a.err
#SBATCH --export=NONE
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=s.rasp@lmu.de 
#SBATCH --job-name=leps160531
    
# load modules
module load icc/16.0.2 intelmpi/5.1.1 
module load netcdf/4.4.0-icc-16 grib_api/1.15.0-icc-16 grib_dwd/20110128-icc-16
    
# perform the actual work
echo "Current task is $SLURM_ARRAY_TASK_ID ..."


# This is a runscript (a shell script) to interpolate COSMO-7km data to COSMO-2.8km 
# grid to use as initial and boundary conditions
# Comments by Stephan Rasp, LMU, s.rasp@lmu.de


#################################################
# Settings (for convenience all the important settings are defined at the top)
#################################################

# Define path to int2lm executable
INTLMEXE=/home/s/S.Rasp/COSMO/makeint2lm/tstint2lm 

# Define paths to input and output directories
# 1. This is where the ECMWF data is
# Hack to account for two digit numbers in leps ensemble
if [ $SLURM_ARRAY_TASK_ID -gt 9 ]
then
  INDIR=/project/meteo/w2w/A6/cleps_ml/201605/2016053100_cleps/pf$SLURM_ARRAY_TASK_ID/
  
else 
  INDIR=/project/meteo/w2w/A6/cleps_ml/201605/2016053100_cleps/pf0$SLURM_ARRAY_TASK_ID/
fi

# 2. This is where the interpolated output data is supposed to go
OUTDIR=/home/cosmo/stephan.rasp/2016053100/dein//$SLURM_ARRAY_TASK_ID/
# Now let's create this output directory if it doesnt exist yet
mkdir -p $OUTDIR

# Define paths to external file (this is where constant fields are saved)
# Check below if file formats and the type of input is correct
# 2. Directory where output external file is located
OUTEXTDIR=/home/cosmo/stephan.rasp/ext
# 3. Name of output external file
OUTEXTNAME=domain2016061412152.nc
# 4. Grid points of external file
IEEXT=461
JEEXT=501

# Define times
DATEEU=2016053100
DATEDE=2016053103
# Simulation length in hours
HSTOP=21
# Output boundary condition frequency in hours
HINCBOUND=3

# Define input grid
# 1. Input grid points (ie->lon; je->lat; ke-> height)
IEIN=511
JEIN=415
KEIN=40
# 2. Input domain location
LONIN=-15.75
LATIN=-16.125
# 3. Input rotated pole location
POLLONIN=-170.0
POLLATIN=40.0

# Define output grid
# 1. Output grid points
IEOUT=421
JEOUT=461
KEOUT=50
# 2. Output rotated pole location
POLLONOUT=-170
POLLATOUT=40
# 3. Output domain location
LONOUT=-5
LATOUT=-5

# Define how many processors are used in x and y direction
NPX=1
NPY=1
NPIO=0

#################################################
# Change directory and create NAMELIST for INT2LM
#################################################
# Copy this runscript


#Change to working and output directory
cd $OUTDIR

# REMOVE OLD FILES!!! 
rm -f YU* M_*
rm -f INPUT*
rm -f batchjob
rm -f cosmo.out


# Create INPUT Namelist with cat
# This creates a text file which contains all the necessary information 
# for INT2LM in OUTPUT directory

cat > INPUT << end_input
 &CONTRL
  ydate_bd='$DATEEU', ydate_ini='$DATEDE',
  linitial=.TRUE., lboundaries=.TRUE.,
  hstart=0.0, hstop=$HSTOP, hincbound=$HINCBOUND,
  nprocx=$NPX, nprocy=$NPY, nprocio=0,
  yinput_model='COSMO',
  lfilter_oro=.true., lfilter_pp=.true., lbalance_pp=.true.,
  eps_filter=0.1, norder_filter=5,
  ilow_pass_oro=4, ilow_pass_xso=5,
  lasync_io=.false., lreorder=.false., lroutine=.false., ltime_mean=.true.,
  lmulti_layer_in=.true., lmulti_layer_lm=.true.,
  lprog_qi=.true., lprog_qr_qs=.TRUE., lprog_rho_snow=.TRUE.,
  lforest=.true., lt_cl_corr=.false., luvcor=.true.,
  lvertwind_ini=.true., lvertwind_bd=.true.,
  rxso_mask=625.0,
  idbg_level=2,
 /
 &GRID_IN
  startlon_in_tot=$LONIN, startlat_in_tot=$LATIN,  
  pollat_in=$POLLATIN,        pollon_in=$POLLONIN,
  dlat_in=0.0625,        dlon_in=0.0625,
  ie_in_tot=$IEIN, je_in_tot=$JEIN, ke_in_tot=$KEIN,
 /
 &LMGRID
  startlat_tot=$LATOUT, startlon_tot=$LONOUT,
  pollat=$POLLATOUT, pollon=$POLLONOUT,
  dlon=0.025, dlat=0.025,
  ielm_tot=$IEOUT, jelm_tot=$JEOUT, kelm_tot=$KEOUT,
  ivctype=2, vcflat=11357.0,
  vcoord_d=22000.00,21000.00,20028.57,19085.36,18170.00,17282.14,
           16421.43,15587.50,14780.00,13998.57,13242.86,12512.50,
           11807.14,11126.43,10470.00, 9837.50, 9228.57, 8642.86,
            8080.00, 7539.64, 7021.43, 6525.00, 6050.00, 5596.07,5162.86,
            4750.00, 4357.14, 3983.93, 3630.00, 3295.00, 2978.57,2680.36,
            2400.00, 2137.14, 1891.43, 1662.50, 1450.00, 1253.57,1072.86,
             907.50,  757.14,  621.43,  500.00,  392.50,  298.57, 217.86,
             150.00,   94.64,   51.43,   20.00,    0.00,
 /
 &DATABASE
 /
 &DATA
  ie_ext=$IEEXT, je_ext=$JEEXT,
  ylmext_lfn='$OUTEXTNAME',
  ylmext_cat='$OUTEXTDIR',
  ylmext_form_read='ncdf',
  yinext_lfn='lfff00000000c',
  yinext_form_read='grb1',
  yinext_cat='$INDIR',
  yin_cat='$INDIR',
  yin_form_read='grb1',
  ylm_cat=$OUTDIR',
  yinput_type='forecast',
  nprocess_ini = 137, nprocess_bd = 138, 
 /
 &PRICTR
 /
end_input


# Now all the settings for the INT2LM run are complete and saved in the 
# INPUT namelist file. 
# If you run the INTLMEXE file in this directory now it should work.

# What follows below are setting for the cluster and the parallel environment.
# This is specific for each cluster.

ulimit -s unlimited 
mpirun $INTLMEXE

